### ISSUE TITLE
"Update File Upload Status" need "fileUploadCompletionStatus"

### ISSUE THREAD

**Issue by pandazzurro** [Microsoft/azure-docs.it-it#36]
In this document:
https://docs.microsoft.com/en-us/rest/api/iothub/httpruntime#HttpRuntime_UpdateFileUploadStatus 
"Update File Upload Status" **need** object: "fileUploadCompletionStatus".
What format does?

**Comment by Sneezry** [comment]
Hi Andrea,

fileUploadCompletionStatus is in format of

{
“correlationId”: “xxx”,
“isSuccess”: true,
“statusCode”: 200,
“statusDescription”: “xxx”
}

If you get error Http request require field “fileUploadCompletionStatus”, you should forget to post data.

Zhe
